name: Programmatically validate a non-existing code in 'Australian Immunisation Register Vaccine' CodeSystem

on: 
  [push, pull_request]
  
jobs:

  request:

    runs-on: ubuntu-latest

    steps:
      
      - name: check out repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: POST to http://tx.fhir.org
        id: request
        uses: fjogeleit/http-request-action@v1.9.2
        
        with:
          url: 'http://tx.fhir.org/r4/ValueSet/$validate-code'
          method: 'POST'
          contentType: 'application/fhir+json'
          file: "${{ github.workspace }}/REST/parameter-air-validate-code-fail.json"

      - name: Show response
        env:
          RESULT: ${{ fromJson(steps.request.outputs.response).parameter["name"="result"].valueBoolean }}
          # MESSAGE: ${{ fromJson(steps.request.outputs.response).Parameters.parameter[1].valueString }}
          # CAUSE: ${{ fromJson(steps.request.outputs.response).Parameters.parameter[2].valueString }}
        run: |
          echo ${{ steps.request.outputs.response }}
          echo $RESULT
          # echo $MESSAGE
          # echo $CAUSE
