name: Programmatically expand 'Australian Immunisation Register Vaccine' CodeSystem

on: 
  [push, pull_request]
  
jobs:

  request:

    runs-on: ubuntu-latest

    steps:
      
      - name: check out repo under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: POST to http://tx.fhir.org
        id: request
        uses: fjogeleit/http-request-action@v1.9.2
        
        with:
          url: 'http://tx.fhir.org/r4/ValueSet/$expand'
          method: 'POST'
          ignoreStatusCodes: '422'
          contentType: 'application/fhir+json'
          file: "${{ github.workspace }}/REST/parameter-air-expansion.json"

      - name: Check response
        env:
          RESOURCE: ${{ fromJson(steps.request.outputs.response).resourceType }}
        run: |
          echo ${{ steps.request.outputs.response }}
          $RESOURCE == "ValueSet"